### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/generic-data-index-bundle#209] opened 2024-09-12 07:30 UTC
Platform version 2024.2 (Pimcore 11.3.2.1)

1. Add this bundle to the bundles.php file:
```
<?php

return [
    \Pimcore\Bundle\GenericDataIndexBundle\PimcoreGenericDataIndexBundle::class => ['all' => true],
    \Pimcore\Bundle\EcommerceFrameworkBundle\PimcoreEcommerceFrameworkBundle::class => ['all' => true],
    \CustomerManagementFrameworkBundle\PimcoreCustomerManagementFrameworkBundle::class => ['all' => true],
    \Pimcore\Bundle\ApplicationLoggerBundle\PimcoreApplicationLoggerBundle::class => ['all' => true],
    \Pimcore\Bundle\WebToPrintBundle\PimcoreWebToPrintBundle::class => ['all' => true],
    \Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    \WorkflowBundle\WorkflowBundle::class => ['all' => true],
    \Pimcore\Bundle\EnterpriseSubscriptionToolsBundle\PimcoreEnterpriseSubscriptionToolsBundle::class => ['all' => true],
    \Pimcore\AssetMetadataClassDefinitionsBundle\PimcoreAssetMetadataClassDefinitionsBundle::class => ['all' => true],
    \Pimcore\Bundle\SeoBundle\PimcoreSeoBundle::class => ['all' => true],
    \Pimcore\Bundle\SimpleBackendSearchBundle\PimcoreSimpleBackendSearchBundle::class => ['all' => true],
    \Pimcore\Bundle\ObjectMergerBundle\ObjectMergerBundle::class => ['all' => true],
    \Pimcore\Bundle\TinymceBundle\PimcoreTinymceBundle::class => ['all' => true],
    \Pimcore\Bundle\DataHubBundle\PimcoreDataHubBundle::class => ['all' => true],
    \Pimcore\Bundle\ElasticsearchClientBundle\PimcoreElasticsearchClientBundle::class => ['all' => true],

// ... some bundles hidden for brevity
];
```

2. Run `composer require pimcore/generic-data-index-bundle`

3. Run `bin/console pimcore:bundle:install PimcoreGenericDataIndexBundle`

And this results in the following error:
```

In MappingException.php line 26:

  The class 'SeoBundle\Model\ElementMetaData' was not found in the chain configured namespaces Pimcore\Bundle\GenericDataIndexBundle\Entity


pimcore:bundle:install [-f|--fail-without-error] [--no-post-change-commands] [--no-assets-install] [--no-cache-clear] [--] <bundle>
```

**Comment by mattamon** [comment] 2024-09-12 11:27
Hey @NiklasBr 

thank you for rising this issue with us.

We tried to reproduce the error but were not able to.
We installed the demo-enterprise and the public demo and added the GenericDataIndexBundle. 
We did not encounter this error. 

What we found so far is, that the class `SeoBundle\Model\ElementMetaData` does not even exist in any Pimcore Repository. The only occurence we could find was the `Pimcore\Model\DataObject\Data\ElementMetadata`.

Can you please check where this class is coming from? 
Maybe there is a namespace import missing somewhere. At least I only encountered these kind of errors when the namespaces were not correct.

**Comment by NiklasBr** [comment] 2024-09-12 11:51
Thanks for the quick response!

I have been testing this further and think it is some incompatibility with [dachcom-digital/pimcore-seo](https://github.com/dachcom-digital/pimcore-seo) which we have been using for a while:

a. Running this PimcoreGenericDataIndexBundle and the SeoBundle at the same time causes the exception to be thrown.
b. Running only SeoBundle has no issue.
c. Running only PimcoreGenericDataIndexBundle seems to work.

**Comment by mattamon** [comment] 2024-09-12 11:56
I guess maybe you should open up an issue at [dachcom-digital/pimcore-seo](https://github.com/dachcom-digital/pimcore-seo)

Maybe they can provide a fix or if it is not fixable at their codebase, we can come back to this issue? 

WDYT?

**Comment by NiklasBr** [comment] 2024-09-12 12:10
Maybe @solverat has an idea?

**Comment by solverat** [comment] 2024-09-12 12:27
@NiklasBr, @mattamon yes, it's because this bundle introduces a dedicated entity manager (I don't know why, though. I'm pretty sure this bundle doesn't need a custom entity manager).

https://github.com/pimcore/generic-data-index-bundle/blob/1757342b228dd9ec81a5c586962656c2550f1cc9/config/doctrine.yaml#L1-L12

However, to fix this, you have to define the default entity manager explicitly:

```yaml
# app/config/config.yaml
doctrine:
    orm:
        default_entity_manager: default
```

**Comment by mattamon** [comment] 2024-09-12 12:29
@solverat thanks for the quick response! 

@markus-moser I think you have to tackle this question please. 

@NiklasBr https://github.com/pimcore/generic-data-index-bundle/issues/164 There is already an issue, it also breaks CoreShop. Guess we can close this issue then since its actually a duplicate, right?

**Comment by NiklasBr** [comment] 2024-09-12 13:08
Thanks a lot @solverat!

@mattamon I think so.

**Comment by mattamon** [comment] 2024-09-12 13:17
Duplicate of #164

**Closed as completed by mattamon** 2024-09-12 13:17 UTC
Labels: Pimcore:Backlog
