### ISSUE TITLE
Failed to parse field of type [date] with format [strict_date]

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/generic-data-index-bundle#235] opened 2024-10-25 07:59 UTC
Version: Pimcore 2024.3, generic-data-index-bundle: 1.2.1
 
Steps to reproduce:

- Create a brick with a Date field with Column Type DATE
- Create an object with that brick

```
/**
 * Fields Summary:
 * - dateOfBirth [date]

mysql> select * from object_brick_store_dtypepersonalid_document where id = 53\G
                id: 53
         fieldname: docType
       dateOfBirth: 2024-10-25
```
Result:
```
{
    "failures": [
        {
            "index": "pimcore_document-even",
            "id": "53",
            "cause": {
                "type": "mapper_parsing_exception",
                "reason": "failed to parse field [standard_fields.docType.DTypePersonalID.dateOfBirth] of type [date] in document with id '53'. Preview of field's value: '1729807200'",
                "caused_by": {
                    "type": "illegal_argument_exception",
                    "reason": "failed to parse date field [1729807200] with format [strict_date]",
                    "caused_by": {
                        "type": "date_time_parse_exception",
                        "reason": "Text '1729807200' could not be parsed at index 0"
                    }
                }
            },
            "status": 400
        }
	]
}

```

**Comment by morgannilsson** [comment] 2024-10-25 11:40
The error also occurs on Date fields on objects.

**Comment by lukmzig** [comment] 2024-10-28 07:06
@morgannilsson thank you for reporting, I am closing this issue as this is a duplicate of https://github.com/pimcore/generic-data-index-bundle/issues/233

**Closed as completed by lukmzig** 2024-10-28 07:06 UTC

**Comment by morgannilsson** [comment] 2024-10-28 09:41
I think my issue is resolved but manually saving classes. Reported in https://github.com/pimcore/pimcore/issues/17776
